src/Entity/Taxref.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaxrefRepository")
 */
class Taxref
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $famille;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lb_nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_fr;

    public function getId()
    {
        return $this->id;
    }

    public function getFamille(): ?string
    {
        return $this->famille;
    }

    public function setFamille(string $famille): self
    {
        $this->famille = $famille;

        return $this;
    }

    public function getLbNom(): ?string
    {
        return $this->lb_nom;
    }

    public function setLbNom(string $lb_nom): self
    {
        $this->lb_nom = $lb_nom;

        return $this;
    }

    public function getNomFr(): ?string
    {
        return $this->nom_fr;
    }

    public function setNomFr(string $nom_fr): self
    {
        $this->nom_fr = $nom_fr;

        return $this;
    }

}

src/Form/BackOffice/ImageType.php
<?php

namespace App\Form\BackOffice;

use App\Entity\Article;
use App\Entity\Image;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ImageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('imageFile', FileType::class,[
                'label' => false,
                'required' => false,
            ])
            ->add('alt')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Image::class,
        ]);
    }
}

src/Controller/ObservationController.php
<?php

namespace App\Controller;

use App\Entity\Newsletter;
use App\Entity\Observation;
use App\Form\FrontOffice\ObservationType;
use App\Form\NewsletterType;
use App\Repository\ObservationRepository;
use App\Repository\UserRepository;
use App\Services\FlashesService;
use App\Services\UserService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Yaml\Yaml;

/**
 * Class HomeController
 * @package App\Controller
 * @Route("/observation")
 */
class ObservationController extends Controller
{
    /**
     * @var UserService
     */
    private $userService;
    /**
     * @var FlashesService
     */
    private $flashesService;

    public function __construct(UserService $userService, FlashesService $flashesService)
    {
        $this->userService = $userService;
        $this->flashesService = $flashesService;
    }

    /**
     * @Route(name="observationIndex")
     */
    public function observationIndex(ObservationRepository $observationRepository, Request $request)
    {
        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        $newsletter =  new Newsletter();
        $newsletterForm =   $this->createForm(NewsletterType::class, $newsletter);
        $newsletterForm->handleRequest($request);

        if ($newsletterForm->isSubmitted() && $newsletterForm->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($newsletter);
            $em->flush();

            $request
                ->getSession()
                ->getFlashBag()
                ->add('info', 'Bravo, vous venez de vous abonner à notre Newsletter')
            ;
        }

        return $this->render('views/observation/observationInfo.html.twig',[
            'observations' => $observationRepository->findBy([],['date'=>'desc']),
            'newsForm'      => $newsletterForm->createView(),
            'elementPage'  => Yaml::parseFile($this->getParameter('kernel.project_dir').'/translations/observation.yaml'),
            'flashs'       => $this->flashesService->getFlashes($request)
        ]);
    }

    /**
     * @Route("/creer", name="observationCreate")
     */
    public function observationCreate(Request $request, UserRepository $userRepository)
    {
        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        $observation = new Observation();
        $observationForm = $this->createForm(ObservationType::class, $observation);
        $observationForm->handleRequest($request);

        if ($observationForm->isSubmitted() && $observationForm->isValid()) {
            if (!$request->getSession()->has('user')){
                $request
                    ->getSession()
                    ->getFlashBag()
                    ->add('warning', 'Vous devez être <strong>connecté</strong> pour poster une observation');
            }else{
                $observation
                    ->setAuthor($userRepository->find($request->getSession()->get('user')->getId()))
                ;
                $em = $this->getDoctrine()->getManager();
                $em->persist($observation);
                $em->flush();

                $request
                    ->getSession()
                    ->getFlashBag()
                    ->add('warning', 'Votre observation sera prise en compte sous peu')
                ;
            }
        }


        return new Response($this->renderView('views/observation/observationCreate.html.twig',[
            'elementPage'       => Yaml::parseFile($this->getParameter('kernel.project_dir').'/translations/observation.yaml'),
            'observationForm'   => $observationForm->createView(),
            'flashs'            => $this->flashesService->getFlashes($request)
        ]));
    }

}

src/Controller/backOffice/ArticleController.php
<?php

namespace App\Controller\backOffice;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use App\Services\FlashesService;
use App\Services\UserService;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin")
 */
class ArticleController extends Controller
{

    /**
     * @var UserService
     */
    private $userService;
    /**
     * @var FlashesService
     */
    private $flashesService;

    public function __construct(UserService $userService, FlashesService $flashesService)
    {
        $this->userService = $userService;
        $this->flashesService = $flashesService;
    }

    /**
     * @Route(name="article_index", methods="GET")
     */
    public function article_index(ArticleRepository $articleRepository, Request $request, PaginatorInterface $paginator): Response
    {
        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        $q = $request->query->get('q');
        $queryBuilder = $articleRepository->getArticleWithSearchQueryBuilder($q);

        $pagination = $paginator->paginate(
            $queryBuilder, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            10/*limit per page*/
        );

        return $this->render('back-office/article/index.html.twig', [
            'pagination'    => $pagination
        ]);
    }

    /**
     * @Route("/article/new", name="article_new", methods="GET|POST")
     */
    public function article_new(Request $request): Response
    {
        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($article);
            $em->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('back-office/article/new.html.twig', [
            'article' => $article,
            'form'    => $form->createView(),
        ]);
    }

    /**
     * @Route("/article/{id}", name="article_show", methods="GET")
     */
    public function article_show(Article $article, Request $request): Response
    {
        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        return $this->render('back-office/article/show.html.twig', ['article' => $article]);
    }

    /**
     * @Route("/article/{id}/edit", name="article_edit", methods="GET|POST")
     */
    public function article_edit(Request $request, Article $article): Response
    {
        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_edit', ['id' => $article->getId()]);
        }

        return $this->render('back-office/article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods="DELETE")
     */
    public function article_delete(Request $request, Article $article): Response
    {
        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($article);
            $em->flush();
        }

        return $this->redirectToRoute('article_index');
    }
}

src/Controller/backOffice/CategoryController.php
<?php

namespace App\Controller\backOffice;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use App\Services\FlashesService;
use App\Services\UserService;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/categories")
 */
class CategoryController extends Controller
{

    /**
     * @var UserService
     */
    private $userService;
    /**
     * @var FlashesService
     */
    private $flashesService;

    public function __construct(UserService $userService, FlashesService $flashesService)
    {
        $this->userService = $userService;
        $this->flashesService = $flashesService;
    }

    /**
     * @Route("/", name="category_index", methods="GET")
     */
    public function category_index(CategoryRepository $categoryRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $q = $request->query->get('q');
        $queryBuilder = $categoryRepository->getCategoryWithSearchQueryBuilder($q);

        $pagination = $paginator->paginate(
            $queryBuilder, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            10/*limit per page*/
        );

        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        return $this->render('back-office/category/index.html.twig', [
            'pagination' => $pagination
        ]);
    }

    /**
     * @Route("/new", name="category_new", methods="GET|POST")
     */
    public function category_new(Request $request): Response
    {
        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($category);
            $em->flush();

            return $this->redirectToRoute('category_index');
        }

        return $this->render('back-office/category/new.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="category_show", methods="GET")
     */
    public function category_show(Category $category, Request $request): Response
    {
        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        return $this->render('back-office/category/show.html.twig', ['category' => $category]);
    }

    /**
     * @Route("/{id}/edit", name="category_edit", methods="GET|POST")
     */
    public function category_edit(Request $request, Category $category): Response
    {
        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('category_edit', ['id' => $category->getId()]);
        }

        return $this->render('back-office/category/edit.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="category_delete", methods="DELETE")
     */
    public function category_delete(Request $request, Category $category): Response
    {
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($category);
            $em->flush();
        }

        return $this->redirectToRoute('category_index');
    }
}

src/Controller/backOffice/NewsletterController.php
<?php

namespace App\Controller\backOffice;

use App\Entity\Newsletter;
use App\Form\Newsletter1Type;
use App\Repository\NewsletterRepository;
use App\Services\FlashesService;
use App\Services\UserService;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin")
 */
class NewsletterController extends Controller
{
    /**
     * @var UserService
     */
    private $userService;
    /**
     * @var FlashesService
     */
    private $flashesService;

    public function __construct(UserService $userService, FlashesService $flashesService)
    {
        $this->userService = $userService;
        $this->flashesService = $flashesService;
    }

    /**
     * @Route("/newsletter",name="newsletter_index", methods="GET")
     */
    public function newsletter_index(NewsletterRepository $newsletterRepository, Request $request): Response
    {
        if (!$this->userService->isAuthorized($request, __FUNCTION__)){
            $this->flashesService->setFlashes($this->userService->getFlash());
            return $this->redirectToRoute('home');
        };

        file_put_contents('emailsNewsLetter.txt', $this->renderView('views/newsletterRender.html.twig',[
            'mails' => $newsletterRepository->findAll()
        ]));
        return $this->render('back-office/newsletter/index.html.twig', [
            'newsletters' => $newsletterRepository->findAll()
        ]);
    }

}

templates/back-office/observation/_delete_form.html.twig
<form method="post" action="{{ path('observation_delete', {'id': observation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ observation.id) }}">
    <div class="text-right">
        <button class="btn btn-danger">Supprimer</button>
    </div>
</form>

templates/back-office/observation/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{{ form_start(form) }}
    <div class="row">

        <div class="col-6">
            <div class="row">
                <div class="card-body col-12 form-group encart">
                    {{ form_row(form.description, {'label':'Description', 'attr':{'novalidate':'true', 'rows':5}}) }}
                </div>
                {% if form.image.vars.data.image.name is defined %}
                    <div class="card-img col-12">
                        <img class="cover-custom-square" src="{{ asset('img/'~form.image.vars.data.image.name ?? 'null') }}" alt="{{ form.image.vars.data.alt ?? 'null'}}">
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="card-body col-6 form-group encart">
            {{ form_row(form.species, {'label':'Espèce', 'attr':{'urlautocomplete' : "/autocomplete_species"}}) }}
            {{ form_row(form.date, {'label':'Date de l\'observation'}) }}
            {{ form_row(form.checked, {'label':'Valider'}) }}
            {{ form_row(form.author, {'label':'Auteur de l\'observation'}) }}
            {{ form_row(form.image, {'label':'Image'}) }}
            {{ form_row(form.verifiedBy, {'label':'Vérifié par'}) }}
            {{ form_row(form.position, {'label':false}) }}
        </div>
    </div>

    {{ form_widget(form) }}
    <div class="text-right">
        <button class="btn btn-success mb-3">{{ button_label|default('Sauvegarder') }}</button>
    </div>
{{ form_end(form) }}

templates/back-office/observation/edit.html.twig
{% extends 'back-office/base.html.twig' %}

{% block title %}Observation{% endblock %}

{% block body %}
    <a class="btn-outline-dark" href="{{ path('observation_index') }}">
        <i class="far fa-arrow-alt-circle-left"></i> Observations
    </a>
    <h1 class="text-center">Observation</h1>

    {{ include('back-office/observation/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('back-office/observation/_delete_form.html.twig') }}

{% endblock %}

{% block javascripts %}
{{ parent() }}
    <script>
        $(document).ready(function(){
            let $autocompleteSpecies = $("#observation_species");
            $autocompleteSpecies
            // .val("")
                .autocomplete({
                    source: document.getElementById('observation_species').getAttribute('urlAutocomplete'),
                    minLength: 2
                });
        });
    </script>
{% endblock %}

templates/back-office/observation/index.html.twig
{% extends 'back-office/base.html.twig' %}

{% block title %}Observations{% endblock %}

{% block body %}
    <h1 class="text-center">Observations</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Espèces</th>
                <th>Date</th>
                <th>Validé</th>
                <th>image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for observation in pagination %}
            <tr>
                <td>{{ observation.species.nomFr }}</td>
                <td>{{ observation.date ? observation.date|date('Y-m-d') : '' }}</td>
                <td>{{ observation.checked ? 'Oui' : 'Non' }}</td>
                <td>
                    {% if observation.image.image is defined %}
                        <img src="{{ asset('img/'~observation.image.image.name) }}" height="50px">
                        {% else %}
                            <img src="{{ asset('imgSite/default_bird.png') }}" height="50px">
                    {% endif %}
                </td>
                <td class="text-right pr-3 action">
                    <div class="action">
                        <a class="btn btn-info" href="{{ path('observation_show', {'id': observation.id }) }}">
                            <i class="far fa-eye"></i>
                        </a>
                        <a class="btn btn-primary" href="{{ path('observation_edit', {'id': observation.id}) }}">
                            <i class="fas fa-edit"></i>
                        </a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="col-12 text-right">
        <a class="btn btn-success" href="{{ path('observation_new') }}">
            Nouveau <i class="fas fa-plus"></i>
        </a>
    </div>

    <!-- Pagination -->
    <ul class="pagination justify-content-center mb-4">
        {{ knp_pagination_render(pagination) }}
    </ul>
{% endblock %}

templates/back-office/observation/new.html.twig
{% extends 'back-office/base.html.twig' %}

{% block title %}Nouvelle observation{% endblock %}

{% block body %}
    <a class="btn-outline-dark" href="{{ path('observation_index') }}">
        <i class="far fa-arrow-alt-circle-left"></i> Observations
    </a>
    <h1 class="text-center">Nouvelle observation</h1>
    {{ include('back-office/observation/_form.html.twig') }}
{% endblock %}

templates/back-office/observation/show.html.twig
{% extends 'back-office/base.html.twig' %}

{% block title %}Observation{% endblock %}

{% block body %}
    <a class="btn-outline-dark" href="{{ path('observation_index') }}">
        <i class="far fa-arrow-alt-circle-left"></i> Observations
    </a>
    <h1 class="text-center">Observation</h1>

    {% if observation.image.image is defined %}
        <figure>
            <img src="{{ asset('img/'~observation.image.image.name) }}" alt="{{ observation.image.image.name }}" width="100%">
            <figcaption>{{ observation.image.alt }}</figcaption>
        </figure>
    {% endif %}

    <table class="table">
        <tbody>
            <tr>
                <th>Description</th>
                <td>{{ observation.description }}</td>
            </tr>
            <tr>
                <th>Espèce</th>
                <td>{{ observation.species.nomFr ~' ('~ observation.species.lbNom ~ ')'}}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ observation.date ? observation.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date de modification</th>
                <td>{{ observation.updatedAt ? observation.updatedAt|date('Y-m-d') : '' }}</td>
            </tr>
                {% if observation.position.address is defined %}
                <tr>
                    <th>Position</th>
                    <td>{{ observation.position.address.villeNom ?? 'null' }}</td>
                </tr>
                {% endif %}
            <tr>
                <th>Checked</th>
                <td>{{ observation.checked ? 'Oui' : 'Non' }}</td>
            </tr>
        </tbody>
    </table>

    {{ include('back-office/observation/_delete_form.html.twig') }}
{% endblock %}